export * from "./Nav/nav"
export * from "./Home/home"
export * from "./Carrousel/carrousel"
export * from "./Projects/projects"
export * from "./Experience/work_experience"
export * from "./About Me/about_me"